Srpg 39  character base
NBC-SRPG/SRPG pull request #16
Opened 2024-03-12 03:19 UTC by chai227chai

## 개요

캐릭터 클래스와 스킬 클래스 새로 생성했습니다.
캐릭터 클래스의 경우 prefab으로 모든 캐릭터의 오브젝트를 미리 만들어 둔 후 
dictionary나 list를 통해 관리하는 식으로 만들고 싶어서 Monobehavior를 상속 시켜놨는데, 추후 설계 방향에 따라서 변경될 수 있습니다.

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [x] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. (ex. feature/SRPG-11-UIBase)
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-12 03:24 UTC, chai227chai commented on Assets/Scripts/Objects/Characters/CharacterInBattle/CharacterBase.cs
> +}
이 부분에 굳이 행동 별 함수를 다시 선언한 이유는 같은 상황일 때 발동하는 효과들을 한꺼번에 관리하기 위해서 입니다

2024-03-12 03:41 UTC, SeRDic0705 reviewed
너무 멋지게 작업해주셨는데요?
- 양이 너무 많아서 변경사항을 확인이 힘들어요(PR 조금씩 나눠서 자주하면 좋을 것 같아요)
- 주석이 있는곳도 있고 없는 곳도 있는데, 없는곳에서 어떤 로직인지 한눈에 알기가 어려워요

메서드 별로만이라도 주석을 추가해주실 수 있을까요?

2024-03-12 03:53 UTC, GeCrabKani requested changes
MapManager에 중복된 코드가 있습니다.

    Vector2Int[] directions = new Vector2Int[]
    {
        new Vector2Int(1, 0), new Vector2Int(-1, 0),
        new Vector2Int(0, 1), new Vector2Int(0, -1),
        new Vector2Int(1, 1), new Vector2Int(-1, 1),
        new Vector2Int(1, -1), new Vector2Int(-1, -1),
    };

    foreach (Vector2Int dir in directions)
    {
        Vector2Int tileToCheck = originTile + dir;
        if (map.ContainsKey(tileToCheck))
        {
        }
    }
와 같이 방향 벡터 배열을 이용하면 중복 코드를 줄일 수 있습니다.
-----
CharacterController에 PlayerPhase 타입이 클래스 밖에 public 타입으로 선언되어있습니다.
타 스크립트에서 사용이 필요하다면 Utils의 Constants에 선언해주세요.
해당 스크립트에서만 사용한다면 클래스 내부에 private로 선언해주세요.

CharacterSO의 Enum들도 해당
-----
MapTiles의 Awake에서 매니저 Init()을 실행하고 있습니다.
Managers 스크립트의 get 부분에서 Init을 실행 후 return을 해주고 있습니다.
타 스크립트에서 사용 시 Init 순서를 신경쓰지 않아도 괜찮습니다.

2024-03-12 06:46 UTC, chai227chai reviewed
피드백 부분을 수정했습니다.

2024-03-12 07:03 UTC, GeCrabKani approved these changes

2024-03-12 10:16 UTC, SeRDic0705 commented on Assets/Scripts/MapScripts/CharacterController/CharacterController.cs
>      private void GetMoveRangeTile()// �̵� ���� �Ÿ� ������
주석들이 깨져서 나와요

인코딩 설정이 변경된 것 같은데 UTF-8인지 확인해서 수정 부탁드려요

2024-03-12 10:30 UTC, chai227chai commented on Assets/Scripts/MapScripts/CharacterController/CharacterController.cs
>      private void GetMoveRangeTile()// �̵� ���� �Ÿ� ������
파일 변경 완료 했습니다

2024-03-12 11:30 UTC, SeRDic0705 approved these changes

2024-03-13 10:27 UTC, jhwoo944 approved these changes

2024-03-13 10:27 UTC, merged