feature/SRPG-25-BattleSystem
NBC-SRPG/SRPG pull request #32
Opened 2024-03-20 11:03 UTC by chai227chai

## 개요

체력과 캐릭터 사망 처리를 위한 HealthSystem을 추가했습니다.
서버와의 연동을 고려하고, 전투 애니메이션을 매끄럽게 연계하기 위해 전투 로직을 변경했습니다.
캐릭터의 반격 패시브에 대한 테스트를 진행했습니다.

## PR 유형
어떤 변경 사항이 있나요?

- [X] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [X] 코드 리팩토링
- [X] 주석 추가 및 수정
- [ ] 문서 수정
- [X] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다. (ex. feature/SRPG-11-UIBase)
- [X] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-03-20 12:05 UTC, jhwoo944 approved these changes

2024-03-20 12:28 UTC, GeCrabKani requested changes
아직 사용하지는 않는 것 같지만 TakeHealthBar(int n) 코루틴의 역할이 n의 체력 변화량을 받고 이를 체력바 이미지에 적용하는 것일까요?
만약 MaxHealth = 100, n = 5와 같이 들어와서 number = 0.05가 된다면 while에서 0.1씩 변화를 주고있기 때문에 탈출할 수 없습니다.

1. number = 0.05, tmp = 0
2. number = 0.05 tmp = 0.1
2. number = 0.05 tmp = 0.2 ... 무한 반복

TakeHealthBar() 코루틴의 경우에는 healthBar에 0.1씩 변화를 주고 있습니다.
먼저 int 체력에 변화를 주고 이미지에 0.1씩 변화를 주어 점점 차오르거나 깍여내리는 연출을 하려는 것으로 보입니다.
만약 HealthRatio = 0.55, healthBar.fillAmount = 0.5인 경우라면
healthBar.fillAmount = 0.5
healthBar.fillAmount = 0.6 ... 식으로 회복하게 됩니다.
이 경우에도 무한 루프를 빠져나갈 수 없습니다.

TakeDamageHealthBar()나 HealHealthBar()를 TakeDamage()와 HealHealth()의 안에 두지 않고 따로 둔 이유가 있을까요??

2024-03-20 16:12 UTC, chai227chai commented
> 아직 사용하지는 않는 것 같지만 TakeHealthBar(int n) 코루틴의 역할이 n의 체력 변화량을 받고 이를 체력바 이미지에 적용하는 것일까요? 만약 MaxHealth = 100, n = 5와 같이 들어와서 number = 0.05가 된다면 while에서 0.1씩 변화를 주고있기 때문에 탈출할 수 없습니다.
> 
> 1. number = 0.05, tmp = 0
> 2. number = 0.05 tmp = 0.1
> 3. number = 0.05 tmp = 0.2 ... 무한 반복
> 
> TakeHealthBar() 코루틴의 경우에는 healthBar에 0.1씩 변화를 주고 있습니다. 먼저 int 체력에 변화를 주고 이미지에 0.1씩 변화를 주어 점점 차오르거나 깍여내리는 연출을 하려는 것으로 보입니다. 만약 HealthRatio = 0.55, healthBar.fillAmount = 0.5인 경우라면 healthBar.fillAmount = 0.5 healthBar.fillAmount = 0.6 ... 식으로 회복하게 됩니다. 이 경우에도 무한 루프를 빠져나갈 수 없습니다.
> 
> TakeDamageHealthBar()나 HealHealthBar()를 TakeDamage()와 HealHealth()의 안에 두지 않고 따로 둔 이유가 있을까요??

원래 쓰려다가 버그때문에 빼버리고 그부분을 해결하고 다시 쓰려고 했습니다. 이제 뭐가 문제였는지 알겠네요
체력바의 갱신이 데미지 처리와 동시에 일어나지 않는 이유는 애니메이션과 ui의 프레임을 맞추기 위함입니다.
먼저 데미지 처리가 일어나고 애니메이션이 재생되기 때문에 먼저 체력바가 깎여버리면 애니메이션 재생될 때는 체력이 깎여있는 채로 보이거든요

2024-03-21 05:29 UTC, SeRDic0705 approved these changes

2024-03-21 05:29 UTC, SeRDic0705 commented on Assets/Scripts/Managers/BattleManager.cs
> +        //이 부분은 서버에서 처리한 뒤 클라이언트로 전달하도록 후에 변경(치명타 발생 확률 때문)
서버까지 고려해서 변경하신 점 좋습니다만 pvp서버는 4주차에나 시작할 것 같아요..

클라이언트에서 전투 로직을 처리하는 pve의 경우에는 어떻게 처리할까요?

어차피 pve와 pvp의 턴 진행방식도 차이나니까, 전투 진입시 pve인지 pvp인지를 enum으로 가지고 있고, type에 따라 로직을 분리한다든가? 등의 방식을 고민해봐야 할 것 같네요

2024-03-21 05:29 UTC, SeRDic0705 commented on Assets/Scripts/Objects/CharacterSkill/Passive/PassiveAbilityBase.cs
> +    public override void OnTakeDamage(CharacterBase enemy)// 반격 테스트
직관성을 위해서 반격이나 회피 등의 기능은 넣지 않았는데

관련 특성이나 스킬을 보유한 캐릭터를 출시한다면 필요할 것 같네요

2024-03-21 06:20 UTC, chai227chai commented on Assets/Scripts/Managers/BattleManager.cs
> +        //이 부분은 서버에서 처리한 뒤 클라이언트로 전달하도록 후에 변경(치명타 발생 확률 때문)
아마 pve pvp 똑같이 데미지 처리는 서버에서 할 것 같습니다.
대신 pve냐 pvp냐에 따라 AI의 행동값을 받냐, 플레이어의 입력값을 반냐 차이만 있을 것 같아요

2024-03-21 10:23 UTC, GeCrabKani approved these changes

2024-03-21 10:23 UTC, merged