Srpg 77 tileset 메인 퀘스트 1-1 ~ 1-5 타일셋 배치 완료
NBC-SRPG/SRPG pull request #46
Opened 2024-04-08 12:25 UTC by jhwoo944

## 개요

 - 메인 퀘스트 1-1 부터 1-5까지의 타일맵 배치 작업을 완료했습니다. 
 0-Scenes / Test / TileTestScene / MainQuest에서 확인할 수 있습니다.
 칸 당 타일 크기는 16x16 pixel 입니다.
 (맵 구조에 대한 설명은 슬랙 - 파일링크 - 파밍 / 모험 스테이지 기획서 PPT를 참고해주세요.)

 - 타일셋 에셋과 팔레트를 모아놓은 폴더 TileSets을 추가했습니다.
 - 아래의 내용을 적용했습니다.
 1. projectSetting -> Graphics Trasparency Sort Axis의 Y값 1로 변경
 2. Tilemap Renderer Mode Mode Individual로 변경

 - 애니메이션 타일을 적용했으나 현재 Develop 브랜치에 오류가 있는 관계로 테스트해보지는 못했습니다.

Todo.
 - 파밍 스테이지 4종 타일셋 배치하기
 - 타일셋 배치한 맵을 토대로 전투 테스트 해보기
 - 적절한 적 / 맵 기믹 / 스테이지 클리어 조건 / 클리어 보상 / 스토리를 배치하고 실제 스테이지로 완성시키기

*참고용으로 각 맵 별 사진 첨부합니다.
 - 1-1
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/9056e632-76a8-4ba6-8492-01d2f636eadc)
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/9bb19f74-718f-46d4-9449-491328d81d5c)

 - 1-2
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/ce1649d3-6e12-43bb-8f2f-80fb4a357a5a)
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/6553b337-40a6-4999-aae3-0de8d9995895)

 - 1-3
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/a2b8d837-4fce-4138-887b-59e196dacaf7)
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/386cd69f-d5cd-442c-a77c-cb96c29a796a)

 - 1-4
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/969c33fa-aae3-4db1-ab91-791666d46916)
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/23960729-114b-44a5-aa93-b90c46dfa375)

 - 1-5
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/782eff87-35db-410b-8d91-005f13721e66)
![image](https://github.com/NBC-SRPG/SRPG/assets/128718414/9d193c32-66b0-44d4-9040-7d916596d1a8)

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [x] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. (ex. feature/SRPG-11-UIBase)
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-04-08 12:32 UTC, chai227chai approved these changes

2024-04-09 01:20 UTC, GeCrabKani approved these changes

2024-04-11 02:57 UTC, SeRDic0705 requested changes
이전에 말했던대로, 타일셋폴더는  ignore하고, 맵은 프리팹으로Addressable에 올려주세요~
로딩이너무 오래걸려요 ㅠㅠ
![image](https://github.com/NBC-SRPG/SRPG/assets/49552752/905cdfd6-950a-4bb7-ae12-5e5f33b36dff)

2024-04-21 14:42 UTC, closed without merging

2024-04-21 14:42 UTC, jhwoo944 commented
타일셋 작업물은 Feature-3에 merge 되어 있습니다.
혹은 TileSet-ingoreTest 브런치를 참고하면 됩니다.